name: CI

on: [push, pull_request]

jobs:
  CI:
    name: "Linux x64 (Ubuntu 26.04) - Python ${{ matrix.python-version }}"
    runs-on: ubuntu-26.04
    strategy:
      fail-fast: false
      matrix:
        # Only test supported Python versions:
        # https://endoflife.date/python
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends libvips

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Type check with mypy
        if: "!contains(matrix.python-version, 'pypy')"
        run: |
          pip install mypy numpy pillow requests types-requests
          mypy pyvips/*.pyi --no-error-summary
          mypy examples/*.py --no-error-summary

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
